### ISSUE TITLE
Publish new version on crates.io

### ISSUE THREAD

**Issue by Chleba** [mic90/tokio-wifiscanner#4]
Hi,
I can see that some PR are merged but last published version 0.2.1 is from 4.years ago.
Could you please publish new version with windows mod fixed ?
I'm using `tokio-wifiscanner` for my tool - `netscanner` (https://github.com/Chleba/netscanner), and right now I have almost finished fix for MacOS v14.4> where `airport` is no longer supported.
Right now I have my own version of `tokio-wifiscanner` implemented inside of `netscanner`, but I would like to contribute to "official" library but I would like to see some activity.
So if I may ask - is this project still alive or should I publish my version of crate package ? 

Thanks

**Comment by mic90** [comment]
Bumped the version, thanks for the input again :)

**Comment by Chleba** [comment]
Great - thank You very much. I own You a beer :)
